version: "3.9"
services:
  api:
    build: .
    image: kofi-premium-manager:latest
    container_name: kofi-premium-api
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_PREFIX=${API_PREFIX:-/v1}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL_SECONDS=${REDIS_TTL_SECONDS:-3600}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE:-kofi_premium_users}
      # Use AWS shared config via profile inside the container
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_SDK_LOAD_CONFIG=${AWS_SDK_LOAD_CONFIG:-1}
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      # Mount host AWS config/credentials for the appuser
      - ${HOME}/.aws:/home/appuser/.aws:ro

  redis:
    image: redis:7-alpine
    container_name: kofi-premium-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
