version: "3.9"
services:
  api:
    build: .
    image: paypal-premium-manager:latest
    container_name: paypal-premium-api
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_PREFIX=${API_PREFIX:-/v1}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL_SECONDS=${REDIS_TTL_SECONDS:-3600}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE:-paypal_premium_users}
      # Only env-based credentials are used; profiles are disabled
      # PayPal credentials
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_BASE_URL=${PAYPAL_BASE_URL:-https://api-m.sandbox.paypal.com}
      # Uvicorn
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT_HTTP=8080
      - UVICORN_WORKERS=${UVICORN_WORKERS:-2}
    # No direct host port exposure; traffic goes through nginx
    depends_on:
      - redis
    volumes: []

  nginx:
    image: nginx:alpine
    container_name: paypal-premium-nginx
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
      # - "443:443"  # uncomment if enabling HTTPS in nginx config
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./certs:/etc/nginx/certs:ro  # mount when enabling HTTPS

  redis:
    image: redis:7-alpine
    container_name: paypal-premium-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
