version: "3.9"
services:
  api:
    build: .
    image: paypal-premium-manager:latest
    container_name: paypal-premium-api
    restart: unless-stopped
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-prod}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_PREFIX=${API_PREFIX:-/v1}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_TTL_SECONDS=${REDIS_TTL_SECONDS:-3600}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE:-paypal_premium_users}
      # Use AWS shared config via profile inside the container
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_SDK_LOAD_CONFIG=${AWS_SDK_LOAD_CONFIG:-1}
      # PayPal credentials
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_BASE_URL=${PAYPAL_BASE_URL:-https://api-m.sandbox.paypal.com}
      # Uvicorn / TLS
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT_HTTP=8080
      - UVICORN_PORT_HTTPS=8443
      - UVICORN_WORKERS=${UVICORN_WORKERS:-2}
      - ENABLE_TLS=${ENABLE_TLS}
      - SSL_CERTFILE=${SSL_CERTFILE:-/certs/cert.pem}
      - SSL_KEYFILE=${SSL_KEYFILE:-/certs/key.pem}
    ports:
      - "8080:8080"   # HTTP
      - "8443:8443"   # HTTPS (optional)
    depends_on:
      - redis
    volumes:
      # Mount host AWS config/credentials for the appuser
      - ${HOME}/.aws:/home/appuser/.aws:ro
      # Mount TLS certs dir (expects cert.pem and key.pem or adjust paths)
      - ./certs:/certs:ro

  redis:
    image: redis:7-alpine
    container_name: paypal-premium-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
