#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # install required packages
  - apt install -y docker.io
  - apt install -y docker-compose
  - apt install -y unzip
  - apt install -y python3.12-venv

  # Stuff required for newer docker compose version
  - apt install -y ca-certificates curl gnupg

  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg

  - CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $CODENAME stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt update
  - apt install -y docker-compose-plugin

  # Custom AWS CLI installation
  - echo "[CUSTOM] Pulling down aws cli"
  - curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - rm -rf awscliv2.zip
  - rm -rf aws

  - echo "[CHECKPOINT]"
  - cd /opt
  - git clone https://github.com/chang432/paypal_premium_manager.git
  - cd paypal_premium_manager
  - python3 -m venv venv
  - venv/bin/pip install -r requirements.txt

  - reboot

  - chmod +x /opt/paypal_premium_manager/start_cloud.sh
  - (crontab -l 2>/dev/null; echo "*/1 * * * * /opt/paypal_premium_manager/start_cloud.sh >> /var/log/start_cloud.log 2>&1") | crontab -